apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: v2.6.1
    proxyProtocol:
      enabled: true
      trustedIPs:
        - 10.0.0.0/8
    forwardedHeaders:
      enabled: true
      trustedIPs:
        - 10.0.0.0/8
    ssl:
      enabled: true
      permanentRedirect: false
    additionalArguments:
      - --certificatesresolvers.traefikresolver.acme.email=info@alex-stadler.com
      - --certificatesresolvers.traefikresolver.acme.storage=/data/acme.json
      - --certificatesresolvers.traefikresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.traefikresolver.acme.tlschallenge
    
    persistence:
      enabled: true
      path: /data
